ass8: program.o digraph.o circle.o

	g++ -std=c++11 digraph.o program.o circle.o -o ass8

digraph.o: digraph.cpp

	g++ -c -std=c++11 digraph.cpp

program.o: program.cpp

	g++ -c -std=c++11 program.cpp

circle.o: circle.cpp

	g++ -c -std=c++11 circle.cpp
